FROM node:10

LABEL maintainer "Society of Software Engineers"

# API_ROOT `--build-arg=api_root=http://localhost:3000/api/v2`
ARG api_root
ENV API_ROOT $api_root

RUN echo fs.inotify.max_user_watches=582222 >> /etc/sysctl.conf

# refresh container when changes occur
RUN npm install -g nodemon

# Build the app
COPY ./ /app

WORKDIR /app
RUN rpm install --warn

CMD [ "nodemon", "server.js" ]
